export const problems = [
    {
      //熟語の構造
      type:'IdiomStructure',
      body:'次の5つの熟語の構造について、',
      statement:['因果','機微','美醜','日没','着衣'],
      choices:[''],
      solution:50
    },
    {
      //3文の穴埋め
      type:'BlankFixOfThreeSentences',
      body:'日本のシュトは東京',
      statement:'カタカナを漢字に直した時、正しいものを答えなさい',
      choices:[],
      solution:156
    },
    {
      type:'select',
      body:'偶数を選びなさい',
      statement:'',
      choices:[1,2,3,4,5],
      solution:[2,4]
    },
  ];
