export const problems = [
    {
      type:'IdiomStructure',
      body:'次の熟語',
      statement:'',
      choices:[],
      solution:50
    },
    {
      type:'radio',
      body:'日本のは東京',
      statement:'カタカナを漢字に直した時、正しいものを答えなさい',
      choices:[],
      solution:156
    },
    {
      type:'select',
      body:'偶数を選びなさい',
      statement:'',
      choices:[1,2,3,4,5],
      solution:[2,4]
    },
  ];
