export const problems = [
    {
      type:'radio',
      body:'10×5を計算しなさい',
      choices:[15,5,50,2],
      solution:50
    },
    {
      type:'radio',
      body:'12×13を計算しなさい',
      choices:[1,25,156,180],
      solution:156
    },
    {
      type:'select',
      body:'偶数を選びなさい',
      choices:[1,2,3,4,5],
      solution:[2,4]
    },
  ];
